spring:
  application:
    name: aikun-helper
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: <You API Key here>
      embedding-model:
        model-name: text-embedding-v4
        api-key: <You API Key here>
      bigmodel:
        api-key: <Your Api Key>
      streaming-chat-model:
        model-name: qwen-max
        api-key: <Your Api Key>
server:
  port: 8080
  servlet:
    context-path: /api

